apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "circleci-runner.fullname" . }}
  labels:
    {{- include "circleci-runner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "circleci-runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "circleci-runner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: circleci-runner
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "CIRCLECI_RESOURCE_CLASS"
              valueFrom:
                secretKeyRef:
                  key: resourceClass
                  name: config-values
            - name: "CIRCLECI_API_TOKEN"
              valueFrom:
                secretKeyRef:
                  key: runnerToken
                  name: config-values
            {{- if .Values.agentVersion }}
            - name: "agent_version"
              value: "{{ .Values.agentVersion }}"
            {{- end }}
            {{- if .Values.dindSidecar }}
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            {{- end }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - ps -ef | grep circleci-launch-agent
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.dindSidecar }}
        - name: dind-daemon 
          image: "{{ .Values.dindSidecar.image.repository }}:{{ .Values.dindSidecar.image.tag }}"
          imagePullPolicy: {{ .Values.dindSidecar.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          volumeMounts:
            {{- .Values.dindSidecar.volumeMounts | toYaml | trim | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes: 
      {{- .Values.dindSidecar.volumes | toYaml | trim | nindent 8 }}
